### ISSUE TITLE
Improve HelloWorld ViewScoped example

### ISSUE THREAD

**Issue by barsk** [skuzzle/guice-jsf#2]
I would like to suggest improving the ViewScoped example by adding a counter variable in the HelloWorldBean. Displaying that counter in index.xhtml and have a commandButton which increments the counter and returns null (to navigate back to the same page). That will demonstrate that ViewScoped works as it should. Reloading the page resets the counter, while submitting the form will not.

And by changing the scope annotation in HelloWorldBean between RequestScoped, SessionScoped and ViewScoped it is easy to see the effect of the selected scope.

**Comment by skuzzle** [comment]
Excellent idea. I've adjusted the sample accordingly
